title: opyate.com
email: opyate@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Juan M Uys\' personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: opyate
github_username:  opyate
google_analytics: UA-28222168-1
# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
theme: minima
plugins:
  - jekyll-feed
collections:
  doodles:
    output: true
    permalink: /:collection/:path
  ml:
    output: true
    permalink: /:collection/:path
  made:
    output: true
    permalink: /:collection/:path
  chirps:
    output: false
  posts:
    output: true
    permalink: /:collection/:path
  photograms:
    output: true
    permalink: /:collection/:path
  quotes:
    output: true
    permalink: /:collection/:path
  work:
    output: true
    permalink: /:collection/:path
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
